# Generated by Django 4.1.3 on 2022-11-18 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='like',
            field=models.ManyToManyField(blank=True, null=True, to='main.student'),
        ),
    ]
